#!/bin/bash

where=/root/demo-server-service

rsync -rLEu $(dirname ${0})/{main.native,data} ${where}/deploy/ || exit 1
svc -d ${where} || exit 1
svc -u ${where} || exit 1
svstat ${where} || exit 1

echo -e '\033[32m' "ok." '\033[0m'
